### ISSUE TITLE
기본 브랜치의 이름을 `master`에서 `main`으로 변경함에 따른 업데이트

### ISSUE THREAD

**Issue by smilee** [CodeSoom/git-training#22]
기본 브랜치의 이름을 `master`에서 `main`으로 변경함에 따른 업데이트가 레포지토리에는 이미 반영이 되어있으나 문서에는 반영이 되어있지 않습니다. 이에 따라 문서의 `master`를 `main`으로 변경할 것을 요청합니다. 🤔 

참고자료:
https://github.com/github/renaming

**Comment by hannut91** [comment]
이런 이 레포를 깜박했네요! 감사합니다!

**Comment by hannut91** [comment]
반영했습니다 감사합니다 ㅎㅎ
